module.exports = [

[5,'lines_chaos_within_order'],
[40,'grid_bubbles'],
[30,'grid_superposition'],
 [20,'web_diamond'],
 [60,'drop_dandelion'],
 [70,'spatter_variants'],
 [80,'grid_world.jpg'],
 [1000,'grid_fade_h'],
  [140,'drop_ice_h'],
  [160,'grid_maze_h'],
  [180,'drop_aphelion_h'],
  [90,'grid_cloth_h'],
  [200,'web_wheel_h'],
   [150,'drop_iris_h'],
   [220,'random_stripes_h'],
   [7,'grid_fade_h'],
   [250,'grid_signals_h'],
   [100,'drop_starry_night'],
   [190,'lines_1_h'],
   [210,'drop_arrows_h'],
    [270,'grid_mat_h'],
]
